-- PLATFORM : MySQL

CREATE TABLE USER_INFO (
	ID INT(11) AUTO_INCREMENT NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	USER_PASSWORD VARCHAR(256) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL,
	USER_PHONE VARCHAR(13),
	USER_EXT VARCHAR(512),
	REG_DATE DATETIME DEFAULT NOW(),
	UPT_DATE DATETIME DEFAULT NOW(),
	PRIMARY KEY(ID)	
) ENGINE=INNODB DEFAULT CHARSET = UTF8;


CREATE TABLE REQUEST_INFO (
	ID INT(11) AUTO_INCREMENT NOT NULL,
	REQUEST_IP VARCHAR(15) NOT NULL,
	REQUEST_METHOD VARCHAR(20) NOT NULL,
	REQUEST_PARAMS VARCHAR(256) NOT NULL,
	REQUEST_DATE DATETIME DEFAULT NOW(),
	PRIMARY KEY(ID)
) ENGINE=INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE RESPONSE_INFO (
	ID INT(11) AUTO_INCREMENT NOT NULL,
	REQUEST_ID INT(11) DEFAULT 0 NOT NULL,
	RESPONSE_CONSTANT VARCHAR(20) NOT NULL,
	ERROR_NAME VARCHAR(1024),
	ERROR_STACK_TRACE VARCHAR(4000),
	RESPONSE_DATA VARCHAR(512) NOT NULL,
	RESPONSE_DATE DATETIME DEFAULT NOW(),
	PRIMARY KEY(ID)
) ENGINE=INNODB DEFAULT CHARSET = UTF8;